server:
  port: 2904

spring:
  application:
    name: moto-2000

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiration: 5259600000

