export enum MotorcycleType {
  ESPORTIVA = 'ESPORTIVA',
  STREET = 'STREET',
  CUSTOM = 'CUSTOM',
  TURISMO = 'TURISMO',
  OFF_ROAD = 'OFF_ROAD',
  AVENTURA = 'AVENTURA',
  SCOOTER = 'SCOOTER',
  CAFE_RACER = 'CAFE_RACER',
  CHOPPER = 'CHOPPER',
  ELÉTRICA = 'ELÉTRICA'
}
