name: Moto2000 Frontend CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-angular:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular
        run: npm run build -- --configuration production

      - name: Build Docker Image
        run: docker build -t danilodinizs/moto2000-frontend:latest .
